### ISSUE TITLE
mecha not working after install in ubuntu 22 and go 22

### ISSUE THREAD

**Issue by siashish** [hybridgroup/mechanoid#25]
follow the documentation still mecha install not working.
![Screenshot from 2024-03-19 10-18-02](https://github.com/hybridgroup/mechanoid/assets/45603733/c167c635-4778-45a8-b418-0acc17ad0ed4)
if any one know the issue. please help.

**Comment by deadprogram** [comment]
Looks like you might not have the path setup correctly in your installation of Go for binaries, not specific to Mechanoid:

> You need to add $GOPATH/bin (or since GOPATH isn't strictly needed since you're using the default location, just $HOME/go/bin) to your OS $PATH.
> Your shell finds binaries from your main $PATH variable, so that directory needs to be appended to your $PATH before anything can automatically find it

**Comment by siashish** [comment]
![Screenshot from 2024-03-21 09-53-47](https://github.com/hybridgroup/mechanoid/assets/45603733/d1953a2e-49d8-497f-9dd3-af74e9d709d5)
$PATH already set.
Can you elaborate, What I need to change in the system to run the mecha. 
Thanks for your support :)

**Comment by deadprogram** [comment]
You need to add GOBIN to your PATH.

Since yours isn't set explicitly, the default is $GOPATH/bin

**Comment by siashish** [comment]
I added $GOPATH to my OS $PATH, still got the issue.
![Screenshot from 2024-03-21 14-54-18](https://github.com/hybridgroup/mechanoid/assets/45603733/09d471cc-9da9-4c15-b6a2-523e14b6ac3a)

**Comment by deadprogram** [comment]
I think perhaps my comment was not entirely clear.

You need to add whatever path your use of `go install` uses. It is your normal setup for Go that is missing this, not specific to Mechanoid.

**Comment by siashish** [comment]
Thanks for the update.
but now I get while running mecha 
`
ashish@ashish-1-2:~$ mecha new example.com/myproject
gonew github.com/hybridgroup/mechanoid-templates/projects/simple example.com/myproject: exec: "gonew": executable file not found in $PATH

`

**Comment by siashish** [comment]
Thanks for your support :)

**Comment by orsinium** [comment]
> Thanks for your support :)

Does it work for you now?

**Comment by siashish** [comment]
> > Thanks for your support :)
> 
> Does it work for you now?

yes.
